backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "sahil-pages"
    label: "Sahil Style Pages"
    folder: "sahil"
    create: true
    extension: "html"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "sahil-projects"
    label: "Sahil Projects"
    folder: "sahil/projects"
    create: true
    extension: "html"
    editor:
      preview: true
    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Main Index"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
